MvcFuncionarios/Models/Funcionarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFuncionarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public Nullable<int> Departamento_id { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}

MvcFuncionarios/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcFuncionarios.Models;
using MvcFuncionarios.DataContext;

namespace MvcFuncionarios.Controllers
{
    public class FuncionariosController : Controller
    {
        private FuncionariosDataContext db = new FuncionariosDataContext();

        //
        // GET: /Funcionarios/

        public ActionResult Index()
        {
            var funcionarios = db.Funcionarios.Include(f => f.Departamento).Where(s => s.Departamento.Status == true);
            return View(funcionarios.ToList());
        }
        [HttpGet]
        public ActionResult Index(string filtro = null, string buscatxt = null)
        {
            IQueryable<Funcionarios> Resultado;

            if (filtro == "Nome")
            {
                Resultado = (from f in db.Funcionarios
                             where f.Nome.Contains(buscatxt) && f.Departamento.Status == true
                             select f);
            }
            else if (filtro == "Email")
            {

                Resultado = (from f in db.Funcionarios
                             where f.Email.Contains(buscatxt) && f.Departamento.Status == true
                             select f);
            }
            else if (filtro == "Departamento")
            {

                Resultado = (from f in db.Funcionarios
                             join d in db.Departamentos on f.Departamento_id equals d.Id
                             where d.Nome.Contains(buscatxt) && f.Departamento.Status == true
                             select f);
            }
            else if (!String.IsNullOrEmpty(buscatxt))
            {
                Resultado = db.Funcionarios.Where(f => f.Nome.Contains(buscatxt) ||
                f.Email.Contains(buscatxt) ||
                f.Endereco.Contains(buscatxt) ||
                f.Telefone.Contains(buscatxt) ||
                f.Departamento.Nome.Contains(buscatxt) && f.Departamento.Status == true);
            }
            else
            {
                Resultado = db.Funcionarios.Include(f => f.Departamento).Where(s => s.Departamento.Status == true);
            }
            ViewBag.filtro = filtro;
            ViewBag.buscatxt = buscatxt;
            ViewData.Model = Resultado.ToList();

            return View();
        }



        //
        // GET: /Funcionarios/Create

        public ActionResult Create()
        {
            ViewBag.Departamento_id = new SelectList(db.Departamentos.Where(s => s.Status == true), "Id", "Nome");
            return View();
        }

        //
        // POST: /Funcionarios/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Funcionarios funcionarios)
        {
            if (ModelState.IsValid)
            {
                db.Funcionarios.Add(funcionarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Departamento_id = new SelectList(db.Departamentos.Where(s => s.Status == true), "Id", "Nome", funcionarios.Departamento_id);
            return View(funcionarios);
        }

        //
        // GET: /Funcionarios/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            if (funcionarios == null)
            {
                return HttpNotFound();
            }
            var listDepartamentos = new SelectList(db.Departamentos.Where(s => s.Status == true), "Id", "Nome", 2);
            ViewBag.Departamentoid = listDepartamentos;
            return View(funcionarios);
        }

        //
        // POST: /Funcionarios/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Funcionarios funcionarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var listDepartamentos = new SelectList(db.Departamentos.Where(s => s.Status == true), "Id", "Nome", 2);
            ViewBag.Departamentoid = listDepartamentos;
            return View(funcionarios);
        }

        //
        // GET: /Funcionarios/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            if (funcionarios == null)
            {
                return HttpNotFound();
            }
            return View(funcionarios);
        }

        //
        // POST: /Funcionarios/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            db.Funcionarios.Remove(funcionarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcFuncionarios/Views/Funcionarios/Create.cshtml
@model MvcFuncionarios.Models.Funcionarios

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Funcionarios", FormMethod.Post, new { @class = "form-horizontal", @id = "fCreate" }))
 {
    @Html.AntiForgeryToken()




    <div class="form-group">
        <label for="inputNome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-10">
            <input type="text" name="Nome" placeholder="Ex.João da Silva" class="form-control required">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEndereco" class="col-sm-2 control-label">Endereço</label>
        <div class="col-sm-10">
            <input type="text" name="Endereco" placeholder="Ex.Rua forte de alcantara" class="form-control required">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" name="Email" placeholder="Ex.joao@gmai.com" class="form-control required">
        </div>
    </div>
    <div class="form-group">
        <label for="inputTelefone" class="col-sm-2 control-label">Telefone</label>
        <div class="col-sm-10">
            <input type="tel" name="Telefone" placeholder="Ex. (00) 0000-00000" class="form-control phone_with_ddd required">
        </div>
    </div>


    <div class="form-group">
        <label for="inputTelefone" class="col-sm-2 control-label">Departamento</label>
        <div class="col-sm-10">
            @Html.DropDownList("Departamento_id", (IEnumerable<SelectListItem>)ViewBag.Departamento_id, new { Class = "form-control" })

        </div>
</div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-primary" value="Adicionar" />
        </div>
    </div>

 }

        <div>
            @Html.ActionLink("Voltar", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

MvcFuncionarios/Views/Funcionarios/Delete.cshtml
@model MvcFuncionarios.Models.Funcionarios

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Tem certeza de que deseja Deletar este Departamento?</h3>
<fieldset>
    <legend>Funcionarios</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Endereco)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Endereco)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Telefone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Telefone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Departamento.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Departamento.Nome)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcFuncionarios/Views/Funcionarios/Edit.cshtml
@model MvcFuncionarios.Models.Funcionarios

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Funcionarios", FormMethod.Post, new { @class = "form-horizontal", @id = "fCreate" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)


    <div class="form-group">
        <label for="inputNome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-10">
            <input type="text" name="Nome" placeholder="Ex.João da Silva" class="form-control required" value="@Model.Nome" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputEndereco" class="col-sm-2 control-label">Endereço</label>
        <div class="col-sm-10">
            <input type="text" name="Endereco" value="@Model.Endereco" placeholder="Ex.Rua forte de alcantara" class="form-control required">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" name="Email" value="@Model.Email" placeholder="Ex.joao@gmai.com" class="form-control required">
        </div>
    </div>
    <div class="form-group">
        <label for="inputTelefone" class="col-sm-2 control-label">Telefone</label>
        <div class="col-sm-10">
            <input type="tel" name="Telefone" value="@Model.Telefone" placeholder="Ex. (00) 0000-00000" class="form-control phone_with_ddd required">
        </div>
    </div>


    <div class="form-group">
        <label for="inputTelefone" class="col-sm-2 control-label">Departamento</label>
        <div class="col-sm-10">
            @Html.DropDownList("Departamento_id", (IEnumerable<SelectListItem>)ViewBag.Departamentoid, new { Class = "form-control" })

        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-primary" value="Editar" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcFuncionarios/Views/Funcionarios/Index.cshtml
@model IEnumerable<MvcFuncionarios.Models.Funcionarios>

@{
    ViewBag.Title = "Index";
}

<h2>Funcionarios</h2>

<p>
    @Html.ActionLink("Adicionar novo Funcionario", "Create")
</p>

<div class="panel panel-default">
    <div class="panel-body">
@using (Html.BeginForm("Index", "Funcionarios", FormMethod.Get, new { @class = "form-inline", @id = "fCreate" }))
{
       
            <div class="form-group">
                
                <p class="form-control-static">Filtrar  </p>
            </div>
            <div class="form-group">
                <select class="form-control" name="filtro">
                    <option value="">Selecionar filtro</option=">
                    <option value="Nome">Nome</option>
                    <option value="Email">Email</option>
                    <option value="Departamento">Departamento</option>
                </select>
            </div>
           
            <div class="form-group">

                <input type="text" name="buscatxt" value="@ViewBag.buscatxt"   class="form-control">
            </div>
           
            <button type="submit" class="btn btn-default">Buscar</button>
      
}
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            Nome do Departamento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |

                @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>