MvcFuncionarios/Models/Departamento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFuncionarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}

MvcFuncionarios/Controllers/DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcFuncionarios.Models;
using MvcFuncionarios.DataContext;

namespace MvcFuncionarios.Controllers
{
    public class DepartamentosController : Controller
    {
        private FuncionariosDataContext db = new FuncionariosDataContext();

        //
        // GET: /Departamentos/

        public ActionResult Index()
        {
            return View(db.Departamentos.ToList());
        }

       

        //
        // GET: /Departamentos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Departamentos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                db.Departamentos.Add(departamento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(departamento);
        }

        //
        // GET: /Departamentos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Departamento departamento = db.Departamentos.Find(id);
            if (departamento == null)
            {
                return HttpNotFound();
            }
            ViewData.Model = departamento;
            return View(departamento);
        }

        //
        // POST: /Departamentos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(departamento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(departamento);
        }

        //
        // GET: /Departamentos/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Departamento departamento = db.Departamentos.Find(id);
            if (departamento == null)
            {
                return HttpNotFound();
            }
            return View(departamento);
        }

        //
        // POST: /Departamentos/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Departamento departamento = db.Departamentos.Find(id);
            db.Departamentos.Remove(departamento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcFuncionarios/Views/Departamentos/Create.cshtml
@model MvcFuncionarios.Models.Departamento

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Departamentos", FormMethod.Post, new { @class = "form-horizontal", @id = "dpCreate" }))
{
    @Html.AntiForgeryToken()




    <div class="form-group">
        <label for="inputNome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-10">
            <input type="text" name="Nome" class="form-control required" >
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    @Html.CheckBoxFor(x => x.Status, new { @checked = "checked" }) Status
                </label>
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-primary" value="Adicionar" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcFuncionarios/Views/Departamentos/Delete.cshtml
@model MvcFuncionarios.Models.Departamento

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Tem certeza de que deseja Deletar este Departamento?</h3>
<fieldset>
    <legend>Departamento</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Voltar", "Index")
    </p>
}

MvcFuncionarios/Views/Departamentos/Edit.cshtml
@model MvcFuncionarios.Models.Departamento

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Departamentos", FormMethod.Post, new { @class = "form-horizontal", @id = "dpEdit" }))
{   
  @Html.AntiForgeryToken()


   
       

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label for="inputNome" class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-10">
                <input type="text" name="Nome" value="@Model.Nome" class="form-control required">
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(x => x.Status, new { @checked = "checked" }) Status
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="Editar" />
            </div>
            </div>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcFuncionarios/Views/Departamentos/Index.cshtml
@model IEnumerable<MvcFuncionarios.Models.Departamento>

@{
    ViewBag.Title = "Index";
}

<h2>Departamentos</h2>

<p>
    <a class="btn-floating btn-large waves-effect waves-light red"><i class="mdi-content-add"></i></a>
    @Html.ActionLink("Adicionar novo departamento", "Create")
</p>
<table class="table">
    <tr>
        <th data-field="Nome">
            Nome do Departamento
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            Ações
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Departamentos", new { id = item.Id })"><i class="mdi-file-cloud "></i> Editar |</a>
                <a href="@Url.Action("Delete", "Departamentos", new { id = item.Id })"><i class="mdi-file-cloud "></i> Deletar</a>
            </td>
        </tr>
    }

</table>